os: linux
arch: ppc64le
dist: bionic
sudo: required
# setup travis so that we can run containers for integration tests
services:
  - docker

language: go

go:
  - "1.12.x"

go_import_path: github.com/containerd/

addons:
  apt:
    packages:
      - btrfs-tools
      - libnl-3-dev
      - libnet-dev
      - protobuf-c-compiler
      # - protobuf-compiler
      - python-minimal
      - libcap-dev
      - libaio-dev
      - libprotobuf-c0-dev
      - libprotobuf-dev
      - socat
      - libseccomp-dev
  
  
before_install:
  - wget -c https://github.com/protocolbuffers/protobuf/releases/download/v3.7.1/protoc-3.7.1-linux-ppcle_64.zip
  - sudo unzip protoc-3.7.1-linux-ppcle_64.zip -d /usr/local
  - sudo apt-get install -y btrfs-tools
  - cd $GOPATH/src/github.com/opencontainers
  - git clone https://github.com/opencontainers/runc.git
  - cd runc
  - make
  - sudo make install


script:
  - cd $GOPATH/src/github.com
  - mkdir containerd
  - cd containerd
  - git clone https://github.com/containerd/containerd.git
  - cd containerd
  - git checkout d50db0a42053864a270f648048f9a8b4f24eced3
  #- make VERSION="1.2.6"
  - make
  - sudo make install
  - ls
  - cd bin
  - ls
  - sudo chmod 777 containerd
  - sudo ./containerd
  - sudo ./containerd-shim
  - sudo ./containerd-shim-runc-v1
  - sudo ./containerd-stress
  - ./ctr

  
