os: linux-ppc64le
dist: xenial
sudo: required
# setup travis so that we can run containers for integration tests
services:
  - docker

language: go

go:
  - "1.11.x"

addons:
  apt:
    packages:
      - btrfs-tools
      - libnl-3-dev
      - libnet-dev
      - protobuf-c-compiler
      # - protobuf-compiler
      - python-minimal
      - libcap-dev
      - libaio-dev
      - libprotobuf-c0-dev
      - libprotobuf-dev
      - socat
      - libseccomp-dev
      
before_install:
  - wget -c https://github.com/protocolbuffers/protobuf/releases/download/v3.7.1/protoc-3.7.1-linux-ppcle_64.zip
  - sudo unzip protoc-3.7.1-linux-ppcle_64.zip -d /usr/local
  - sudo apt-get install -y btrfs-tools
  - cd $GOPATH/src/github.com/
  - mkdir opencontainers
  - sudo rm -rf containerd
  - mkdir containerd
  - cd opencontainers
  - git clone https://github.com/opencontainers/runc.git
  - cd runc
  - make
  - sudo make install
  - cd $GOPATH/src/github.com/containerd


script:
  - git clone https://github.com/containerd/containerd.git
  - cd containerd
  - make
