os: linux
arch: ppc64le
dist: bionic
sudo: required
# setup travis so that we can run containers for integration tests
services:
  - docker

language: go

go:
  - "1.14.x"
  
before_install:
  - sudo apt update
  - sudo apt install btrfs-tools libnl-3-dev libnet-dev protobuf-c-compiler python-minimal libcap-dev libaio-dev libprotobuf-c0-dev libprotobuf-dev socat libseccomp-dev
  #- wget -c https://github.com/protocolbuffers/protobuf/releases/download/v3.7.1/protoc-3.7.1-linux-ppcle_64.zip
  #- sudo unzip protoc-3.7.1-linux-ppcle_64.zip -d /usr/local
  - go get github.com/opencontainers/runc
  #- git clone https://github.com/opencontainers/runc.git
  #- cd runc
  - cd $GOPATH/src/github.com/opencontainers/runc
  - make
  - sudo make install

script:
  - cd $GOPATH/src/github.com
  - mkdir containerd
  - cd containerd
  - git clone https://github.com/containerd/containerd.git
  - cd containerd
  #- make VERSION="1.2.6"
  - make
  - sudo make install
  - cd bin
  - ls
  - sudo chmod 777 containerd
  - sudo ./containerd --version
  - sudo ./containerd-shim-runc-v1 -v
  - sudo ./containerd-stress --version
  - ./ctr --version

  
