os: linux-ppc64le
dist: xenial
sudo: required
# setup travis so that we can run containers for integration tests
services:
  - docker

language: go

go:
  - "1.11.x"

go_import_path: github.com/containerd/containerd

addons:
  apt:
    packages:
      - btrfs-tools
      - libnl-3-dev
      - libnet-dev
      - protobuf-c-compiler
      # - protobuf-compiler
      - python-minimal
      - libcap-dev
      - libaio-dev
      - libprotobuf-c0-dev
      - libprotobuf-dev
      - socat
      - libseccomp-dev

env:
  - TRAVIS_GOOS=linux TEST_RUNTIME=io.containerd.runc.v1 TRAVIS_CGO_ENABLED=1
  - TRAVIS_GOOS=linux TEST_RUNTIME=io.containerd.runc.v2 TRAVIS_CGO_ENABLED=1
  - TRAVIS_GOOS=linux TEST_RUNTIME=io.containerd.runtime.v1.linux TRAVIS_CGO_ENABLED=1
  - TRAVIS_GOOS=darwin TRAVIS_CGO_ENABLED=0

before_install:
  - wget -c https://github.com/protocolbuffers/protobuf/releases/download/v3.7.1/protoc-3.7.1-linux-ppcle_64.zip
  - sudo unzip protoc-3.7.1-linux-ppcle_64.zip -d /usr/local
  - sudo apt-get install -y btrfs-tools
  - cd $GOPATH/src/github.com/
  - mkdir opencontainers
  - mkdir containerd
  - cd opencontainers
  - git clone https://github.com/opencontainers/runc.git
  - cd runc
  - sudo make
  - sudo make install
  - cd ..
  - cd containerd


script:
  - git clone https://github.com/containerd/containerd.git
  - cd containerd
  - make
